name: Deploy

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Deploy to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Node, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 14.15.4
          cache: "npm"

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Upload to S3
        run: aws s3 sync public/ s3://{{ secrets.S3_BUCKET_NAME }}
